[768, 896, 1024, 1152, 1280, 1536]
global batch size: 8
[34m[1mwandb[39m[22m: [33mWARNING[39m Config item 'filter_list_seq' was locked by 'sweep' (ignored update).
WARNING:absl:options.experimental_threading is deprecated. Use options.threading instead.
WARNING:tensorflow:From /opt/conda/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/liveness.py:83: Analyzer.lamba_check (from tensorflow.python.autograph.pyct.static_analysis.liveness) is deprecated and will be removed after 2023-09-23.
Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089
WARNING:tensorflow:From /opt/conda/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/liveness.py:83: Analyzer.lamba_check (from tensorflow.python.autograph.pyct.static_analysis.liveness) is deprecated and will be removed after 2023-09-23.
Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089
created dataset iterators
loaded enformer_performer
initialized model
finished loading training/val loop functions
building model
/opt/conda/lib/python3.7/site-packages/keras/initializers/initializers_v2.py:121: UserWarning: The initializer RandomUniform is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  f"The initializer {self.__class__.__name__} is unseeded "
total params: tf.Tensor(103275196, shape=(), dtype=int32)
starting epoch_ 1
WARNING:tensorflow:Gradients do not exist for variables ['enformer_performer/dense_9/kernel:0', 'enformer_performer/dense_9/bias:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss` argument?
WARNING:tensorflow:Gradients do not exist for variables ['enformer_performer/dense_9/kernel:0', 'enformer_performer/dense_9/bias:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss` argument?
WARNING:tensorflow:Gradients do not exist for variables ['enformer_performer/dense_9/kernel:0', 'enformer_performer/dense_9/bias:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss` argument?
WARNING:tensorflow:Gradients do not exist for variables ['enformer_performer/dense_9/kernel:0', 'enformer_performer/dense_9/bias:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss` argument?
[34m[1mwandb[39m[22m: Ctrl + C detected. Stopping sweep.
Exception ignored in: <module 'threading' from '/opt/conda/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
KeyboardInterrupt